services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  llm-enrichment:
     build: .
     depends_on:
       - ollama
     environment:
       - LLM_URL=http://ollama:11434
     volumes:
       - ./data:/app/data
       - ./output:/app/output

volumes:
  ollama_data:
